FROM node:18-alpine as build

ARG API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=$API_BASE_URL

ARG API_CAREER_ENDPOINT
ENV NEXT_PUBLIC_API_CAREER_ENDPOINT=$API_CAREER_ENDPOINT

ARG API_INSIGHT_ENDPOINT
ENV NEXT_PUBLIC_API_INSIGHT_ENDPOINT=$API_INSIGHT_ENDPOINT

ARG API_EXPLORATION_ENDPOINT
ENV NEXT_PUBLIC_API_EXPLORATION_ENDPOINT=$API_EXPLORATION_ENDPOINT

ARG API_CLIENT_ID
ENV NEXT_PUBLIC_API_CLIENT_ID=$API_CLIENT_ID

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm install

COPY . /usr/src/app
RUN npm run build
EXPOSE 3000
CMD [ "npm", "start" ]